# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
    loop_hz: 10
    cycle_time_error_threshold: 1

# Settings for ros_control hardware interface
hardware_interface:
    joints:
        - base_to_lwheel
        - base_to_rwheel
    sim_control_mode: 1 # 0: position, 1: velocity

# Publish all joint states
joint_state_controller:
    type:         joint_state_controller/JointStateController
    publish_rate: 10

mobile_base_controller:
    type: diff_drive_controller/DiffDriveController
    left_wheel  : base_to_lwheel
    right_wheel : base_to_rwheel
    publish_rate: 10.0               # default: 50
    pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    wheel_separation : 0.35
    wheel_radius : 0.045

    linear:
        x:
            has_velocity_limits    : true
            max_velocity           : 1.0  # m/s
            min_velocity           : -1.0 # m/s
            has_acceleration_limits: true
            max_acceleration       : 10.0  # m/s^2
            min_acceleration       : -10.0 # m/s^2
            #has_jerk_limits        : true
            #max_jerk               : 27.0  # m/s^3
    angular:
        z:
            has_velocity_limits    : true
            max_velocity           : 10  # rad/s
            has_acceleration_limits: true
            max_acceleration       : 5  # rad/s^2
            #has_jerk_limits        : true
            #max_jerk               : 2.5  # rad/s^3
